### ISSUE TITLE
Administración de sonarcloud 🔴 

### ISSUE THREAD

**Issue by Eric-Durr** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-c#24]
Buenas tardes,
Tratando de configurar el repositorio de acuerdo al análisis de sonarcloud, en el panel de gestión de la aplicación, no aparece el apartado de administración donde se desactiva el análisis automático y donde se extrae el token de acceso. 

¿Se debe conceder individualmente el permiso o está reservado sólo a una persona en la organización?

Saludos,
Eric Durr Sierra.

![image](https://user-images.githubusercontent.com/44397553/161590593-ad9618b8-77db-4c81-98b9-56eeac7a6e9d.png)

**Comment by esegredo** [comment]
Hola, buenas tardes.

¿Pueden confirmar que ahora ven el botón de administración?

Gracias.
@Eric-Durr

**Comment by Eric-Durr** [comment]
No, sigue sin aparecer en la ventana de control.

Gracias.
@esegredo

**Comment by Eric-Durr** [comment]
Sin embargo, me acabo de dar cuenta de que si que tengo permisos sobre la organización. ¿Tal vez se deben conceder permisos a otro nivel?

**Comment by esegredo** [comment]
¿Si eliminas el proyecto de Sonar Cloud y lo vuelves a intentar crear?

**Comment by Eric-Durr** [comment]
Buenos días.

Lo he arreglado con la opción de administración de organización "restore access" desde la sección de "project management" en el dropdown.

![image](https://user-images.githubusercontent.com/44397553/161727402-a82d05a5-3df9-46ed-8f1d-795f88424b65.png)

![image](https://user-images.githubusercontent.com/44397553/161727554-02470977-6b04-4317-bc5a-f5ab78a1553f.png)
