### ISSUE TITLE
Canciones

### ISSUE THREAD

**Issue by Eric-Durr** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-c#5]
Plantear una estructura o conjunto de estructuras para las canciones

**Comment by jeffperezfrade** [comment]
Desarrollando clase Song directamente desde /src

**Comment by jeffperezfrade** [comment]
La duración pone que se haga en minutos y segundos, la pongo en modo string de manera '2m10s' o en un objeto duration = {min: ' ' , seg: ' ' } ? . O también se podría hacer una clase específica para la duración.

**Comment by amarleo** [comment]
En mi opinión, quizás sería más legible y sencillo proponer la duración como un objeto, tal y como has dicho. Aunque tampoco me disgusta la idea del string :+1:

**Comment by Eric-Durr** [comment]
se puede extraer la duración como atributo de la clase a modo de atributo tipo:

```TypeScript
 get seconds() { return this.duartion; }
 get minutes() { return this.duartion / 60; }
public toString() {
 return `${this.minutes}min ${this.duration - this.minutes * 60}sec`;
}
```
y se puede obtener como objeto, ambos formatos son útiles


```TypeScript
get duration(): { min: number, sec: number } {
  return {
    min: this.minutes,
    sec: (this.duration - this.minutes * 60)
  };
}
```
